# Generated by Django 4.0.1 on 2022-01-20 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(max_length=9000, verbose_name='Текст статьи')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40, verbose_name='Тип зааведения')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('location', models.CharField(max_length=75, verbose_name='Местоположение')),
                ('work_time', models.CharField(max_length=30, verbose_name='Время работы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.placetype')),
            ],
            options={
                'verbose_name_plural': 'Заведения',
            },
        ),
        migrations.CreateModel(
            name='TagSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WishListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(blank=True, null=True, verbose_name='Дата желаемого посещения')),
                ('comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='Пожелания')),
                ('place_of_visiting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='web.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visiting', models.DateField(verbose_name='Дата посещения')),
                ('place_of_visiting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.restaurant')),
            ],
        ),
    ]
