# Generated by Django 4.0.1 on 2022-01-25 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Посещенные заведения', 'verbose_name_plural': 'Посещенные заведения'},
        ),
        migrations.AlterModelOptions(
            name='placetype',
            options={'verbose_name': 'Тип заведения', 'verbose_name_plural': 'Тип заведения'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'verbose_name': 'Список пожеланий', 'verbose_name_plural': 'Список пожеланий'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
