# Generated by Django 4.0.1 on 2022-01-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_history_comment_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Комментарии'),
        ),
    ]
