# Generated by Django 4.0.1 on 2022-01-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_history_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='comment',
            field=models.CharField(default='', max_length=2000, verbose_name='Комментарии'),
        ),
    ]
