# Generated by Django 4.0.1 on 2022-01-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_history_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Комментарии'),
        ),
    ]
