# Generated by Django 4.0.1 on 2022-01-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_history_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='comment',
        ),
    ]
