# Generated by Django 4.0.1 on 2022-01-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_history_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
    ]
