# Generated by Django 4.0.1 on 2022-01-25 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0013_remove_history_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
