# Generated by Django 4.0.1 on 2022-01-26 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_history_comment_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='place_of_visiting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.restaurant', verbose_name='Посещенное заведение'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Фото меню')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.restaurant', verbose_name='Заведение')),
            ],
        ),
    ]
