# Generated by Django 4.0.1 on 2022-01-26 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_history_place_of_visiting_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Фото Меню', 'verbose_name_plural': 'Фото Меню'},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='image',
            new_name='menu_image',
        ),
    ]
