# Generated by Django 4.0.1 on 2022-01-26 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_menu_options_rename_image_menu_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_images', to='web.restaurant', verbose_name='Заведение'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_location', models.CharField(max_length=250, verbose_name='Расположение')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_location', to='web.restaurant', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Фото Меню',
                'verbose_name_plural': 'Фото Меню',
            },
        ),
    ]
