# Generated by Django 4.0.1 on 2022-01-26 10:38

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('web', '0017_alter_menu_place_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Расположение мест на карте', 'verbose_name_plural': 'Расположение мест на карте'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='location',
            name='map_location',
            field=models.TextField(max_length=800, verbose_name='Расположение'),
        ),
    ]
